/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    java
    `maven-publish`
    id("com.diffplug.spotless") version "6.12.0"
    id("org.jetbrains.kotlin.jvm") version "1.8.10"
    id("org.jlleitschuh.gradle.ktlint") version "11.2.0"
    id("org.jetbrains.dokka") version "1.7.20"
}

repositories {
    mavenLocal()
    mavenCentral()
}

group = "info.novatec"
version = "2.0-SNAPSHOT"
description = "camunda-bpmn-documentation-generator"
java.sourceCompatibility = JavaVersion.VERSION_17

dependencies {
    implementation("org.camunda.bpm.model:camunda-bpmn-model:7.18.0")
    compileOnly("org.apache.maven.plugin-tools:maven-plugin-annotations:3.7.1")
    implementation("org.freemarker:freemarker:2.3.32")
    dokkaHtmlPlugin("org.jetbrains.dokka:kotlin-as-java-plugin:1.7.20")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named("build") {
    dependsOn("spotlessApply")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "17"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target("**/*.kt")
        ktlint()
    }
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
}
