# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Git Checkout main project
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '14'
          cache: 'gradle'
      - name: Clean and Build with Gradle Wrapper
        run: ./gradlew clean build
      - name: build and upload maven plugin
        run: ./gradlew buildPluginDescriptor publishToMavenLocal
      - name: git checkout test project
        uses: actions/checkout@v2
        with:
          repository: ahsNT/cbdg-maven-test
          path: test-project
      - name: build test project
        run: cd ./test-project; mvn clean install