# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Git Checkout main project
        uses: actions/checkout@v2
        with:
          path: camunda-bpmn-documentation-generator
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: clean and build camunda-bpmn-documentation-generator
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build publishToMavenLocal
          build-root-directory: ./camunda-bpmn-documentation-generator
      - name: git checkout maven plugin project
        uses: actions/checkout@v2
        with:
          repository: NovatecConsulting/cbdg-maven-plugin
          path: cbdg-maven-plugin
      - name: build cbdg-maven-plugin
        run: cd ./cbdg-maven-plugin; mvn clean install
      - name: git checkout test project
        uses: actions/checkout@v2
        with:
          repository: NovatecConsulting/cbdg-maven-test
          path: cbdg-maven-test
      - name: build cbdg-maven-test
        run: cd ./cbdg-maven-test; mvn clean install